export const USERNAME_LENGTH = 0
export const USERNAME_DOES_NOT_EXIST = 1
export const USERNAME_PASSWORD_MISMATCH = 2
export const USERNAME_ALREADY_TAKEN = 3
export const USERID_DOES_NOT_EXIST = 4
export const UNDEFINED_USERID = 5
export const INVALID_SESSION = 6